workflows:
  unity-ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: "acc1"
    environment:
      xcode: 16.2
      groups:
        - 1DEFAULT
      vars:
        XCODE_PROJECT: "BuildAvia.xcodeproj" #<----------------SET HERE
        XCODE_SCHEME: "BuildAvia" #<----------------SET HERE
        CERTIFICATE_PRIVATE_KEY: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAt90lcv3dzFSkza1C3i5QGtm8odeeukZXLIqgj3trTgUxpZ8p
            pftKvyayHr3HzNdfMWxiAyvzrSZjEWY2AkMpM528GJhm0L2rVrE1bU6E/aFIkiuV
            CES+VHtSIsRKucmBP0sm6CeO9xfM10WHHDNHPdp15G085R56Vm9C1c/CjVdWbCl6
            xP3zvmF5VozAIOj2k73bsEVMweMj+KNh6mdP/2Lf01hNY8NJ13iRIjjMDtqpdtew
            NLJ0xK96sfnIHbRoc+eMsZpmvjStmfRCNyVw1iJnpnyd8DTAtfidUdN1gfxGLQlQ
            S8D52RFd5M7PF7AazMYH5LtsxgGZLkmUtonCHwIDAQABAoIBAANMtanXr6xc2iaq
            PaoDu/Ebx99ZUCJV8AKnwyVxgXFYr7KiFDI4UyZmmQ92oOVyP3zHE9h96GPWbZGJ
            UrtDY79m+4DGZ2avtFgnzs894FzZES3vdXmljuhTf4Ryql9fdXFikqg4vpyrPURE
            TB41q2CW1wjhpkLNGqHEkGWh0qYMxdIyjf7kQddZo2ThGgcbHSA1fTnYbucgCHPS
            Wo9s7mcMv0C3xYM/l+Rkhhpw1Yb1OukLGfV4UukGwCAnCyQMgMrFO7oRUvaCLa/z
            XAXxzs4oFrO0HJPFzm4PXPaUmh0Fu99GppsNIfXe/WlzDGwCV5fkLqkSEMTs8kof
            70k1zlUCgYEA/bGwgSsmRuTJZU7I1GmOiiu5/8V1cq1YAyg6iqyjTw/rTaihE8UH
            Rs/Pf/wvZuhcnJAb3w2hLVv5sivyfNHKfji1bvfTErHIhN8LEP0cSWIlHk+AUufu
            LnNPsYIeC4u4n8eiUxiB5nRh49zaeHBtmJoLKChi7ylOx9lm2+aoEkMCgYEAuYj4
            vXLsxvxQylF7/m314exE4oXNTft8m2tExjFmfG7WAAEyRcZsu4fzZj4F1yG3kkxU
            aEiOOR2SZmOZ4ogYeEj7ahHDJYFde9G0rBcJ81nBKdgFObGr7Y8dNPVAQn+fUYaP
            oOg61CvvnY2HPR/5lt/rPjSN/b9jbuIrKdN+GPUCgYEA/UilVyDUc11CMXIKEgBd
            PlfPuKvUyayFPYmxgPhBh9L18y/TueAxlqItobMPRGfi5rD+EqER9S5pylgUHkh6
            KbDGe8bTpkt3Tik9bDW4Qw/IzU1EagGDDD82JpwpEQ/rQSLYTqweLQ6vGQdL24kr
            8nqBfxNrSynrrJ3CEvRjgu8CgYBkCffc5r/G1zuUq3UJDi9bPvMxlOXLW4OnpaIy
            n2ZcR8L5w6tgtgng4AAcq+qoQhTiPGfyxtRw9YH/1UqfO7S9/tQZMDSh32wRnFQn
            ylBiN44Qytqebi9+6wDbkjWw5XF5Gu4M28sEpiAQOsSl77y7XkdQhjPdkznBCxAt
            AE1olQKBgQCNVm2+36QihKz6mc7J+FTH9vsktTu2amBK8NN5RryiK0dCw8T10v3P
            HqGakd5PsV66tqmynQH3lcyvX3tCMUX/Mt7t86wM/g3AJuR3lMV+HnF3XFOsoA3J
            YnGPAx48nzGyFcc40P0xuv+qDyZjEYwJ/RATAk7m4brrMvCJXxtnFQ==
            -----END RSA PRIVATE KEY-----
        
    scripts:
      - name: Delete derived data
        script: rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files for main target
        script: |
          app-store-connect fetch-signing-files "com.selimAhmed.BuildAvia" \
            --type IOS_APP_STORE \
            --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Set build number manually
        script: agvtool new-version -all 1
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "CODE_SIGN_STYLE=Auto"
      - name: Publish to App Store Connect
        script: |
          app-store-connect publish --path "/Users/builder/clone/build/ios/ipa/BuildAvia.ipa"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
